# yaml-language-server: $schema=schemas/recipe.json

vibversion: 1.0.0

id: vesper-vanilla-desktop
name: Vesper's Vanilla Desktop

stages:
  - id: build
    addincludes: true
    singlelayer: false

    labels:
      maintainer: Maurício Braz

    args:
      DEBIAN_FRONTEND: noninteractive

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    base: ghcr.io/vanilla-os/desktop:main

    modules:
      - name: init
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Custom Actions
      # Custom Actions

      - name: one-password
        type: includes
        includes:
          - modules/one-password.yml

      - name: docker
        type: includes
        includes:
          - modules/docker.yml

      - name: apt
        type: apt
        sources:
          - path: modules/apt.inst

      - name: howdy
        type: meson
        buildflags:
          - --prefix=/usr
          - --buildtype=release
        sources:
          - type: git
            branch: beta
            url: https://github.com/boltgolt/howdy.git

      - name: flatpak
        type: flatpak
        system:
          reponame: flathub
          install:
            - comcom.obsproject.Studio
            - com.github.wwmm.easyeffects
            - com.obsproject.Studio.Plugin.DroidCam
          repourl: https://flathub.org/repo/flathub.flatpakrepo

      - name: presets
        type: shell
        commands:
          - EASY_EFFECTS_FOLDER=/var/lib/flatpak/app/com.github.wwmm.easyeffects/current/active/files/easy-effects/
          - mkdir -p $EASY_EFFECTS_FOLDER/presets && cp -r /usr/share/presets/* $EASY_EFFECTS_FOLDER/
          - chmod -R 755 $EASY_EFFECTS_FOLDER

      # Custom Actions
      # Custom Actions

      - name: set-image-name
        type: shell
        commands:
          - IMAGE_NAME="$(cat /image-info/image-name)"
          - echo custom image name "$IMAGE_NAME"
          - IMAGE_NAME_ESCAPED="$(echo $IMAGE_NAME | sed 's/\//\\\//g')"
          - sed -i "s/changed_automatically_by_vib/$IMAGE_NAME_ESCAPED/g" /usr/share/abroot/abroot.json
          - rm -rf /image-info

      - name: pre-cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: fsguard
        type: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*

includespath: includes.container
