# yaml-language-server: $schema=schemas/recipe.json

vibversion: 1.0.0

id: vesper-vanilla-desktop
name: Vesper's Vanilla Desktop

stages:
  - id: build
    addincludes: true
    singlelayer: false

    labels:
      maintainer: Maurício Braz

    args:
      DEBIAN_FRONTEND: "noninteractive"
      DEBCONF_NONINTERACTIVE_SEEN: "true"

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    base: ghcr.io/vanilla-os/desktop:main

    modules:
      - name: init
        type: shell
        commands:
          - lpkg --unlock
          - apt-get update

      # Custom Actions
      # Custom Actions

      - name: includes
        type: includes
        includes:
          - modules/10-build-essentials.yml
          - modules/50-add-1password.yml
          - modules/50-add-docker.yml
          - modules/60-common.yml
          - modules/75-howdy.yml

      # Custom Actions
      # Custom Actions

      - name: set-image-name
        type: shell
        commands:
          - IMAGE_NAME="$(cat /image-info/image-name)"
          - echo custom image name "$IMAGE_NAME"
          - IMAGE_NAME_ESCAPED="$(echo $IMAGE_NAME | sed 's/\//\\\//g')"
          - sed -i "s/changed_automatically_by_vib/$IMAGE_NAME_ESCAPED/g" /usr/share/abroot/abroot.json
          - rm -rf /image-info

      - name: pre-cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: fsguard
        type: fsguard

        GenerateKey: true
        CustomFsGuard: false

        FilelistPaths: ["/usr/bin"]
        FsGuardLocation: "/usr/sbin/FsGuard"

        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /sources
          - rm -rf /var/tmp/*

includespath: includes.container
